name: "Build"
on:
  push:
jobs:
  build-arm64:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
    name: "Build (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: bluegent
          signingKey: ${{ secrets.CACHIX_SECRET_KEY }} # oop
          cachixArgs: "-v -j8"
      - run: nix build
